[package]
name = "torch-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
cc = "1.0.72"
cfg-if = "1.0.0"
once_cell = "1.8.0"
ureq = { version = "2.3.0", optional = true }
zip = "0.5.13"

[features]
default = ["download-libtorch"]
download-libtorch = ["ureq"]
